---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json
modules:
  - from-file: workstation/common.yaml
  - type: files
    files:
      - source: niri
        destination: /
  - type: dnf
    repos:
      copr:
        - "avengemedia/dms"
        - "yalter/niri"
  - type: dnf
    install:
      packages:
        # Niri
        - "niri"
        # Shell/greeter
        - "quickshell"
        - "dms"
        - "greetd"
        - "dms-greeter"
        # GUI apps
        - "nautilus" # needed for file picker
        # DE essentials
        - "initial-setup"
        - "mako" # notification daemonQ
        - "polkit"
        - "xwayland-satellite"
        - "tuned-ppd"
        - "upower"
        - "adwaita-fonts-all"
        - "adwaita-icon-theme"
        - "desktop-backgrounds-basic"
        - "gvfs"
        - "gvfs-mtp"
        - "gvfs-fuse"
        - "gvfs-nfs"
        - "gvfs-smb"
        - "xdg-desktop-portal-gtk"
        - "xdg-desktop-portal-gnome"
        - "gnome-keyring"
        # Screen recording
        - "grim"
        - "slurp"
        - "wf-recorder"
  - type: systemd
    user:
      enabled:
        - "dsearch.service"
    system:
      enabled:
        - "greetd.service"
        - "initial-setup.service"
