---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json
modules:
  - from-file: workstation/common.yaml
  - type: dnf
    remove:
      packages:
        - "gnome-tweaks"
    install:
      packages:
        - "nautilus-python"
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - "com.mattjakeman.ExtensionManager"
